### ISSUE TITLE
Bed and panel files?

### ISSUE THREAD

**Issue by ricsmo** [3dprintingworld/MULDEX#11]
Maybe I missed them, but I didn't see files for the bed and panels.

I'm currently building a Mulbot and an [MPCNC](https://www.v1engineering.com/specifications/) and would love for the first MPCNC project to be milling the bed and panels for the Muldex.

Will these files be available upon release or does this have to do with sponsorship in any way?

**Comment by 3dprintingworld** [comment]
That sounds like a awesome project!  The files you are looking for are available, see link below. They are 2D detail drawings, if you need a model you can pull it from the step file.  I'll work on changing the titles so they don't say "pre-release" as they have not changed.

https://github.com/3dprintingworld/MULDEX/tree/master/Detailed%20Drawings

**Comment by ricsmo** [comment]
Great. I'm going a bit overboard with building so many things like this lately. I also have a [Ciclop](https://github.com/bqlabs/ciclop) and [Dremel CNC](https://www.thingiverse.com/thing:3004773) that I'm halfway done with so I'll wait until the official release because I have time plus I have to figure out where to put all the new machines :). I found the Muldex looking for Mulbot stuff and was immediately excited. Can't wait for the release. I was going to build [this](https://docs.v1engineering.com/mp3dp/) from the same maker as the MPCNC, but since my main printer is a heavily modified Ender 3 (Duet 2, linear rails, etc.) and I'm building the Mulbot, the Muldex is unlike anything else I'd have so it gets priority. Thanks so much for making these and making them open source. I'm not great at anything CAD yet (even struggle at cutting stl models into 2 pieces to be honest), but since this seems like it's becoming an addition hobby I'll eventually learn and be able to contribute with remixes, addons, etc.  At the minimum maybe I'll publish any customizations I make to my firmware.

**Comment by 3dprintingworld** [comment]
Glad you like the design, I really like it to! It didn't happen like I thought it would but I would consider it released.  Drawing are final, I just need to change the names. If you are considering building one, LDO made a short run of kits you might be interested in.  Links for the kits are in the readme. 

It would be awesome if you want to contribute! I'm exited to hear everyone's feedback and idea's so we can make it even better than it already is. If its mechanical or firmware tweak I'm all ears. We also have a facebook group if your interested in that discussion.

**Comment by 3dprintingworld** [comment]
I have updated all the draws so they no longer say "preliminary".
