### ISSUE TITLE
stepper mounts issue

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#2]
We may have 2 issues with the STL files 22-01 and 23-01:
 - These numbers refer to the U and X axis stepper mounts in the drawings, however they seem to carry the motor higher than the other stepper mounts (24-01 & 25-01), so I believe these are the Y axis mounts.
 - The "groove" aimed to center the stepper motor is 20.2mm wide instead of 22mm in the Nema 17 standard so the motors don't fit. See attached pictures.

![Motor](https://user-images.githubusercontent.com/30982511/84596864-630b4d80-ae60-11ea-9aac-a6700cea8504.jpg)
![22-01](https://user-images.githubusercontent.com/30982511/84596865-643c7a80-ae60-11ea-8ff1-f45cf0bac431.jpg)

**Comment by 3dprintingworld** [comment]
Sorry about that, I remember it now. I forgot to update the design because I never reprinted it and was able to open the parts up with a exacto knife to make it work. I have updated the files for the correct pilot diameter now.

**Comment by ghost** [comment]
Hi John; thanks for the info and for correcting the files.
The online files aren't updated yet.
Do you mean you will update it later?

**Comment by 3dprintingworld** [comment]
Sorry I'm not good with github, I forgot to push the changes or something.... It should be updated now.  If not, let me know.

**Comment by ghost** [comment]
I don't know these GIT things at all so I won't blame you!
That looks way better now, thank you!
