### ISSUE TITLE
Missing STLs

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#3]
I listed the following STLs that are represented in the assembly drawings but currently missing in the GitHub repository.

MULDEX-29-01 REVERSE BOWDEN BRACKET
MULDEX-29-02 EXTRUDER CABLE, RELIF
MULDEX-29-03 EXTRUDER CABLE, CLAMP
MULDEX-29-04 WIRE COMB, FRONT
MULDEX-29-05 WIRE COMB, BACK

MULDEX-33-01 SCRAPPER, FRAME
MULDEX-33-02 PURGE BIN
MULDEX-33-03 SCRAPPER BASE
MULDEX-33-04 SCRAPER KNOB
MULBOT-34 SCRAPPER, FRAME X-AXIS

MULDEX-36-xx LIGHT END BRACKET, RH
MULDEX-36-02 LIGHT END BRACKET, LH

MULDEX-37-01 Y-AXIS SWITCH BRACKET
MULDEX-38 SWITCH BRACKET, LH

**Comment by 3dprintingworld** [comment]
Thanks for finding the missing files, I also fixed the typos. Let me know if you find anymore missing files. 

FYI... The purge buckets assemblies 33 and 34 have not been tested yet. I revised the design from a earlier version but went with the ooze shield instead.

**Comment by ghost** [comment]
Thanks a lot for uploading the files.
Just to let you know, files 07-01 and 34-01 are named MULBOT instead of MULDEX ;-)

**Comment by 3dprintingworld** [comment]
Force of habit...  I already updated the assembly's but forgot the stl's.
