### ISSUE TITLE
U axis carriage set screws placement

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#4]
The set screws of the  axis carriage end up being too short.
![U axis carriage](https://user-images.githubusercontent.com/30982511/85920018-84ad0180-b870-11ea-97ad-0d26cc079e95.png)

**Comment by 3dprintingworld** [comment]
I moved the nut trap on "MULDEX-13-01" to work with the set screw specified in the materials. 

I would not say these set screws are necessary.  The idea is that it squares up the carriage to the bearings as well as removes the slop from the bolt holes which will keep them from loosening.  The down side I noticed if tightened too hard it can cause the carriage to deform.

**Comment by ghost** [comment]
I agree with you and won't re-print this part, but thanks for the next persons building it!
These set screws are one of many details that make this design feel very qualitative and professional.

**Comment by 3dprintingworld** [comment]
Using the set screws to square up the blocks is very common in machine design and I was supersized no one was doing it on 3D printers. The only extra cost being the setscrews, I thought it worth incorporating into the design.
