### ISSUE TITLE
X-axis carriage cover screw holes not blinded

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#5]
I noticed that the screw holes that would normally require supports are generally blinded to prevent the support need, but the one in part MULDEX-12-05 / X-AXIS CARRIAGE COVER aren't.
![image](https://user-images.githubusercontent.com/30982511/85942413-6ce58400-b929-11ea-9437-6e27c708359f.png)

**Comment by 3dprintingworld** [comment]
I had the end of part rolled back and didn't realize it.  Fixed now!

**Comment by ghost** [comment]
Quick and perfect, thank you!
