### ISSUE TITLE
missing STLs

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#6]
The following STLs are listed in the BOM (thanks for releasing it), but not in the STLs on GitHub:
MULDEX-01-03 / PANNEL SUPPORT
MULDEX-03-04 / DUET SPACER
MULDEX-03-08 / WIRE CLIP

**Comment by 3dprintingworld** [comment]
I just added them!

08 was just something I made to keep the wires trapped in the extrusions.  There might be something better already designed on thingiverse, but these seem to work pretty good.

**Comment by ghost** [comment]
Thanks again!
That was probably the last missing STLs.
