### ISSUE TITLE
Typo in config.g?

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#7]
I spotted this in config.g:

_; Drives
M569 P1 S0                                      ; X physical drive 0 goes backwards
M569 P1 S1                                      ; Y right physical drive 1 goes forwards_

Both lines refer to P1 driver.
The first line should probably refer to P0.
I guess that might have an impact on further X/Y functions.

**Comment by 3dprintingworld** [comment]
Oh, wow!  Thanks for pointing this out.

**Comment by 3dprintingworld** [comment]
Strange that the typo did not seem to have any impact, I assume it must of defaulted to a direction when not specified.

**Comment by ghost** [comment]
Fine then, I close the issue
