### ISSUE TITLE
Auto level configuration

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#8]
In config.g you have

> M671 X-20.6:200:420.6 Y14.3:333.3:14.3 S2       ; Locations left, center, right

defining the Z axis locations for the auto leveling process

In bed.g you have

> G30 P0 X200 Y285 Z-99999   ; Probe Middle
> G30 P1 X65 Y15 Z-99999     ; Probe Left
> G30 P2 X385 Y15 Z-99999 S3 ; Probe Right

I read in https://betrue3d.dk/bltouch-on-duet-wifi-configuratio-and-usage/ that the G30 sequence should be the same as in the M671 config. Here it's not.
My G32 command (auto level) wasn't working until I fixed this by putting the "Left" G30 command first in bed.g.

**Comment by 3dprintingworld** [comment]
Strange, It appears to be working properly on my end.  I do still have some height issues but I thought that has something to do with mesh bed leveling not working right, or bubbles under my Buildtak.  I'll change it, at the very least it will be cleaner.  

DC did state this to me on a previous conversation on the Duet forum when I was originally had issues with this feature; "The probe order doesn't matter. But the order of the leadscrew coordinates in the M671 command must match the order of the corresponding motor drivers in the M584 command. No need to change your wiring, just correct one of those commands to match the other."  According to this the order should not matter but he could be wrong.  I'll give it a try tonight, thanks for noting it.

**Comment by ghost** [comment]
You must be right. I think I made other changes at the same time. I probably had something else wrong.

**Comment by 3dprintingworld** [comment]
Either way, thanks for pointing it out.  I appreciate your help!  Im excited to see what else you find.
