### ISSUE TITLE
Z-AXIS MOTOR MOUNT 2 dimension issue

### ISSUE THREAD

**Issue by ghost** [3dprintingworld/MULDEX#9]
On part "MULDEX-17-04" / "Z-AXIS MOTOR MOUNT, 2" I had issues assembling the geared motor because its screw holes's distance to center were too short. I re-drilled it and didn't properly compare with the other Z axis motor mounts because I had already assembled it, but measuring on the STL files tend to confirm that.
No issue with "MULDEX-16-01" / "Z-AXIS MOTOR MOUNT, 1&3".

**Comment by 3dprintingworld** [comment]
Oh sorry about that....  LDO made a mistake on one of the gear motors I was provided and put the holes in the wrong spot. I offset the holes in the design so they line up with the incorrect spacing on the gearbox but I forgot to change it back to the standard hole spacing for others.  I'll update it shortly.

**Comment by 3dprintingworld** [comment]
Ok, all fixed, Changed from the 28mm B.C. to 30mm like it should have been.  I released these last because I knew I needed to update something but it slipped my mind...

**Comment by ghost** [comment]
Thanks for that!

**Comment by ghost** [comment]
I reprinted this part. It's now a perfect fit.
